/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Desktop 1' | 'Desktop 2' | 'Desktop 3' | 'Tablet 1' | 'Tablet 2' | 'Tablet 3' | 'Mobile 1' | 'Mobile 2' | 'Mobile 3'
    "title1"?: string
    "title2"?: string
    "title3"?: string
}

const HeroTitleFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

HeroTitleFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default HeroTitleFramerComponent

