// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e581698183ded160 "ERIS Drexel Drone", do not edit manually */
"use client";

// virtual:image-changer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/l8JS7sKRFYCOL8ZnlWoK/XjYLSjRxwF4WHrf0GSEE/dTlo3yvZZ.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["KRJpZNjW0", "PJhnXyMuc"];
var serializationHash = "framer-WUt10";
var variantClassNames = { KRJpZNjW0: "framer-v-uykodg", PJhnXyMuc: "framer-v-nsab8o" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { delay: 0, duration: 0.4, ease: [0.44, 0, 0.56, 1], type: "tween" };
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { "Desktop 1": "KRJpZNjW0", "Desktop 2": "PJhnXyMuc" };
var getProps = ({ height, id, image, width, ...props }) => {
  return { ...props, rjk_eQu76: image ?? props.rjk_eQu76 ?? { pixelHeight: 1808, pixelWidth: 2400, src: "https://framerusercontent.com/images/blO9S3CbYfXAfqzsNgSGOggU7no.jpeg?scale-down-to=2048", srcSet: "https://framerusercontent.com/images/blO9S3CbYfXAfqzsNgSGOggU7no.jpeg?scale-down-to=512 512w,https://framerusercontent.com/images/blO9S3CbYfXAfqzsNgSGOggU7no.jpeg?scale-down-to=1024 1024w,https://framerusercontent.com/images/blO9S3CbYfXAfqzsNgSGOggU7no.jpeg?scale-down-to=2048 2048w,https://framerusercontent.com/images/blO9S3CbYfXAfqzsNgSGOggU7no.jpeg 2400w" }, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "KRJpZNjW0" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, rjk_eQu76, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "KRJpZNjW0", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-uykodg", className, classNames), "data-framer-name": "Desktop 1", layoutDependency, layoutId: "KRJpZNjW0", ref: refBinding, style: { ...style }, ...addPropertyOverrides({ PJhnXyMuc: { "data-framer-name": "Desktop 2" } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsx(Image, { background: { alt: "", fit: "fill", loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 0 + (((componentViewport?.height || 311.5) - 0 - 339) / 2 + 0 + 0)), pixelHeight: 2400, pixelWidth: 1984, sizes: `calc(${componentViewport?.width || "100vw"} * 0.4)`, ...toResponsiveImage(rjk_eQu76) }, className: "framer-g67yx7", "data-framer-name": "Image", layoutDependency, layoutId: "K6So26LwU", style: { borderBottomLeftRadius: 16, borderBottomRightRadius: 16, borderTopLeftRadius: 16, borderTopRightRadius: 16 }, ...addPropertyOverrides({ PJhnXyMuc: { background: { alt: "", fit: "fill", loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 0 + (((componentViewport?.height || 779.5) - 0 - 339) / 2 + 0 + 0)), pixelHeight: 2400, pixelWidth: 1984, sizes: componentViewport?.width || "100vw", ...toResponsiveImage(rjk_eQu76) } } }, baseVariant, gestureVariant) }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-WUt10.framer-usuk85, .framer-WUt10 .framer-usuk85 { display: block; }", ".framer-WUt10.framer-uykodg { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }", ".framer-WUt10 .framer-g67yx7 { aspect-ratio: 1.5398230088495575 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 312px); overflow: hidden; position: relative; width: 40%; will-change: var(--framer-will-change-override, transform); }", ".framer-WUt10.framer-v-nsab8o .framer-g67yx7 { height: var(--framer-aspect-ratio-supported, 780px); width: 100%; }"];
var FramerdTlo3yvZZ = withCSS(Component, css, "framer-WUt10");
var stdin_default = FramerdTlo3yvZZ;
FramerdTlo3yvZZ.displayName = "Image changer";
FramerdTlo3yvZZ.defaultProps = { height: 311.5, width: 1200 };
addPropertyControls(FramerdTlo3yvZZ, { variant: { options: ["KRJpZNjW0", "PJhnXyMuc"], optionTitles: ["Desktop 1", "Desktop 2"], title: "Variant", type: ControlType.Enum }, rjk_eQu76: { __defaultAssetReference: "data:framer/asset-reference,blO9S3CbYfXAfqzsNgSGOggU7no.jpeg?originalFilename=Modern+Tech+Arrangement.jpeg&preferredSize=auto", title: "Image", type: ControlType.ResponsiveImage } });
addFonts(FramerdTlo3yvZZ, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:image-changer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "B3FNg4k_A": { "path": "/404" }, "I9RkjucP4": { "path": "/legal/:slug" }, "LRbug5v4t": { "path": "/workshops" }, "NyXcQ0q58": { "path": "/workshops/:slug" }, "RW9KK4MDB": { "path": "/contact" }, "augiA20Il": { "path": "/" }, "kSNNxgO_v": { "path": "/about-us" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "B3FNg4k_A": {
          "path": "/404"
        },
        "I9RkjucP4": {
          "path": "/legal/:slug"
        },
        "LRbug5v4t": {
          "path": "/workshops"
        },
        "NyXcQ0q58": {
          "path": "/workshops/:slug"
        },
        "RW9KK4MDB": {
          "path": "/contact"
        },
        "augiA20Il": {
          "path": "/"
        },
        "kSNNxgO_v": {
          "path": "/about-us"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
