// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e581698183ded160 "ERIS Drexel Drone", do not edit manually */
"use client";

// virtual:iphone-mockup
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/dtIkLSI3Ocl4QsfkfYFB/fUeYEZLBpShHgINL0vUA/yDG_ovfTJ.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS, withFX } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var serializationHash = "framer-VAUeT";
var variantClassNames = { agIUPHj1i: "framer-v-2l4yqd" };
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};
var animation = { opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 60 };
var transition2 = { delay: 0.1, duration: 0.6, ease: [0.2, 0.52, 0.3, 0.81], type: "tween" };
var animation1 = { opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition2, x: 0, y: 60 };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, width, ...props }) => {
  return { ...props, AmU1JfYfW: image ?? props.AmU1JfYfW ?? { alt: "", pixelHeight: 2509, pixelWidth: 2074, src: "https://framerusercontent.com/images/YrKYp1GG9SthFQDGGSHNUQC0.png?scale-down-to=1024", srcSet: "https://framerusercontent.com/images/YrKYp1GG9SthFQDGGSHNUQC0.png?scale-down-to=1024 846w,https://framerusercontent.com/images/YrKYp1GG9SthFQDGGSHNUQC0.png?scale-down-to=2048 1692w,https://framerusercontent.com/images/YrKYp1GG9SthFQDGGSHNUQC0.png 2074w" } };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, AmU1JfYfW, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "agIUPHj1i", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-2l4yqd", className, classNames), "data-framer-name": "Desktop", layoutDependency, layoutId: "agIUPHj1i", ref: refBinding, style: { ...style }, children: /* @__PURE__ */ _jsx(ImageWithFX, { __framer__animate: { transition: transition2 }, __framer__animateOnce: true, __framer__enter: animation, __framer__exit: animation1, __framer__styleAppearEffectEnabled: true, __framer__threshold: 0.5, __perspectiveFX: false, __smartComponentFX: true, __targetOpacity: 1, background: { alt: "", fit: "fit", loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 24 + ((componentViewport?.height || 555) - 24 - ((componentViewport?.height || 555) - 24) * 0.7)), pixelHeight: 2509, pixelWidth: 2074, sizes: `max(${componentViewport?.width || "100vw"} - 48px, 1px)`, ...toResponsiveImage(AmU1JfYfW), ...{ positionX: "center", positionY: "bottom" } }, className: "framer-1ol01gx", layoutDependency, layoutId: "fxmtISsUP" }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-VAUeT.framer-13g3vts, .framer-VAUeT .framer-13g3vts { display: block; }", ".framer-VAUeT.framer-2l4yqd { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 555px; justify-content: flex-end; overflow: hidden; padding: 24px 24px 0px 24px; position: relative; width: 470px; }", ".framer-VAUeT .framer-1ol01gx { flex: 1 0 0px; height: 70%; position: relative; width: 1px; }"];
var FrameryDG_ovfTJ = withCSS(Component, css, "framer-VAUeT");
var stdin_default = FrameryDG_ovfTJ;
FrameryDG_ovfTJ.displayName = "Iphone Mockup";
FrameryDG_ovfTJ.defaultProps = { height: 555, width: 470 };
addPropertyControls(FrameryDG_ovfTJ, { AmU1JfYfW: { __defaultAssetReference: "data:framer/asset-reference,YrKYp1GG9SthFQDGGSHNUQC0.png?originalFilename=Group+1.png&preferredSize=auto", __vekterDefault: { alt: "", assetReference: "data:framer/asset-reference,YrKYp1GG9SthFQDGGSHNUQC0.png?originalFilename=Group+1.png&preferredSize=auto" }, title: "Image", type: ControlType.ResponsiveImage } });
addFonts(FrameryDG_ovfTJ, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:iphone-mockup
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "B3FNg4k_A": { "path": "/404" }, "I9RkjucP4": { "path": "/legal/:slug" }, "LRbug5v4t": { "path": "/workshops" }, "NyXcQ0q58": { "path": "/workshops/:slug" }, "RW9KK4MDB": { "path": "/contact" }, "augiA20Il": { "path": "/" }, "kSNNxgO_v": { "path": "/about-us" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "B3FNg4k_A": {
          "path": "/404"
        },
        "I9RkjucP4": {
          "path": "/legal/:slug"
        },
        "LRbug5v4t": {
          "path": "/workshops"
        },
        "NyXcQ0q58": {
          "path": "/workshops/:slug"
        },
        "RW9KK4MDB": {
          "path": "/contact"
        },
        "augiA20Il": {
          "path": "/"
        },
        "kSNNxgO_v": {
          "path": "/about-us"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
