// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e581698183ded160 "ERIS Drexel Drone", do not edit manually */
"use client";

// virtual:logo
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4P8I2AZbMMnK0WqFU2Mg/nquzH9wTJGiSjPabhXVQ/wu0KryvHX.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, Link, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["jY_WhcPQI", "PRa2Z9lWN", "vZVsWLxov"];
var serializationHash = "framer-Ohs1G";
var variantClassNames = { jY_WhcPQI: "framer-v-m7f4bo", PRa2Z9lWN: "framer-v-1gg4wls", vZVsWLxov: "framer-v-7o1xo2" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { Dark: "jY_WhcPQI", Hide: "vZVsWLxov", Light: "PRa2Z9lWN" };
var getProps = ({ height, id, link, width, ...props }) => {
  return { ...props, Gny9Yfhzy: link ?? props.Gny9Yfhzy, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "jY_WhcPQI" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, Gny9Yfhzy, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "jY_WhcPQI", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(Link, { href: Gny9Yfhzy, motionChild: true, nodeId: "jY_WhcPQI", openInNewTab: false, scopeId: "wu0KryvHX", smoothScroll: true, children: /* @__PURE__ */ _jsx(Image, { ...restProps, ...gestureHandlers, as: "a", background: { alt: "", fit: "fill", loading: getLoadingLazyAtYPosition(componentViewport?.y || 0), pixelHeight: 500, pixelWidth: 500, positionX: "left", positionY: "center", src: "https://framerusercontent.com/images/UMNEYA9a7338un3mZqMMd9NpLU.png" }, className: `${cx(scopingClassNames, "framer-m7f4bo", className, classNames)} framer-1t26xlq`, "data-framer-name": "Dark", layoutDependency, layoutId: "jY_WhcPQI", ref: refBinding, style: { opacity: 1, ...style }, variants: { vZVsWLxov: { opacity: 0 } }, ...addPropertyOverrides({ PRa2Z9lWN: { "data-framer-name": "Light", background: { alt: "", fit: "fill", loading: getLoadingLazyAtYPosition(componentViewport?.y || 0), pixelHeight: 500, pixelWidth: 500, positionX: "left", positionY: "center", src: "https://framerusercontent.com/images/oz49dQLS4qK0EfttZdJlRuZxI.png" } }, vZVsWLxov: { "data-framer-name": "Hide" } }, baseVariant, gestureVariant) }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Ohs1G.framer-1t26xlq, .framer-Ohs1G .framer-1t26xlq { display: block; }", ".framer-Ohs1G.framer-m7f4bo { height: 112px; position: relative; text-decoration: none; width: 220px; }"];
var Framerwu0KryvHX = withCSS(Component, css, "framer-Ohs1G");
var stdin_default = Framerwu0KryvHX;
Framerwu0KryvHX.displayName = "Logo";
Framerwu0KryvHX.defaultProps = { height: 112, width: 220 };
addPropertyControls(Framerwu0KryvHX, { variant: { options: ["jY_WhcPQI", "PRa2Z9lWN", "vZVsWLxov"], optionTitles: ["Dark", "Light", "Hide"], title: "Variant", type: ControlType.Enum }, Gny9Yfhzy: { title: "Link", type: ControlType.Link } });
addFonts(Framerwu0KryvHX, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:logo
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "B3FNg4k_A": { "path": "/404" }, "I9RkjucP4": { "path": "/legal/:slug" }, "LRbug5v4t": { "path": "/workshops" }, "NyXcQ0q58": { "path": "/workshops/:slug" }, "RW9KK4MDB": { "path": "/contact" }, "augiA20Il": { "path": "/" }, "kSNNxgO_v": { "path": "/about-us" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "B3FNg4k_A": {
          "path": "/404"
        },
        "I9RkjucP4": {
          "path": "/legal/:slug"
        },
        "LRbug5v4t": {
          "path": "/workshops"
        },
        "NyXcQ0q58": {
          "path": "/workshops/:slug"
        },
        "RW9KK4MDB": {
          "path": "/contact"
        },
        "augiA20Il": {
          "path": "/"
        },
        "kSNNxgO_v": {
          "path": "/about-us"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
