// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e581698183ded160 "ERIS Drexel Drone", do not edit manually */
"use client";

// virtual:scroll
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/h9yy9EXO7bNr6hyZWNF9/aMIAn4f3SfQ9YZ1SuXY7/VNz4Lo5j2.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useOnVariantChange, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["nNDWW0Q0D", "TjB_9fLr7"];
var serializationHash = "framer-3KZCs";
var variantClassNames = { nNDWW0Q0D: "framer-v-qe23ng", TjB_9fLr7: "framer-v-1eng780" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { delay: 0, duration: 0.6, ease: [0.59, 0.42, 0.33, 1.02], type: "tween" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { "Scroll down": "TjB_9fLr7", "Scroll up": "nNDWW0Q0D" };
var getProps = ({ background, border, height, id, width, ...props }) => {
  return { ...props, mYmZWnDfm: border ?? props.mYmZWnDfm ?? { borderColor: "var(--token-d77b16bb-1b8f-4385-b88c-a570a9eef29c, rgb(0, 0, 0))", borderStyle: "solid", borderWidth: 1 }, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "nNDWW0Q0D", xE7or5QVg: background ?? props.xE7or5QVg ?? "var(--token-d77b16bb-1b8f-4385-b88c-a570a9eef29c, rgb(0, 0, 0))" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, mYmZWnDfm, xE7or5QVg, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "nNDWW0Q0D", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onAppearqp45ng = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("TjB_9fLr7"), 2e3);
  });
  const onAppear1jcy9ai = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("nNDWW0Q0D"), 3e3);
  });
  useOnVariantChange(baseVariant, { default: onAppearqp45ng, TjB_9fLr7: onAppear1jcy9ai });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-qe23ng", className, classNames), "data-border": true, "data-framer-name": "Scroll up", "data-highlight": true, layoutDependency, layoutId: "nNDWW0Q0D", ref: refBinding, style: { "--border-bottom-width": (mYmZWnDfm.borderBottomWidth ?? mYmZWnDfm.borderWidth) + "px", "--border-color": mYmZWnDfm.borderColor, "--border-left-width": (mYmZWnDfm.borderLeftWidth ?? mYmZWnDfm.borderWidth) + "px", "--border-right-width": (mYmZWnDfm.borderRightWidth ?? mYmZWnDfm.borderWidth) + "px", "--border-style": mYmZWnDfm.borderStyle, "--border-top-width": (mYmZWnDfm.borderTopWidth ?? mYmZWnDfm.borderWidth) + "px", borderBottomLeftRadius: 100, borderBottomRightRadius: 100, borderTopLeftRadius: 100, borderTopRightRadius: 100, ...style }, ...addPropertyOverrides({ TjB_9fLr7: { "data-framer-name": "Scroll down" } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsx(motion.div, { className: "framer-1mx51vr", "data-framer-name": "Line", layoutDependency, layoutId: "tIiwLf63d", style: { backgroundColor: xE7or5QVg, borderBottomLeftRadius: 10, borderBottomRightRadius: 10, borderTopLeftRadius: 10, borderTopRightRadius: 10 } }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-3KZCs.framer-1qot73h, .framer-3KZCs .framer-1qot73h { display: block; }", ".framer-3KZCs.framer-qe23ng { height: 32px; overflow: visible; position: relative; width: 20px; }", ".framer-3KZCs .framer-1mx51vr { flex: none; height: 6px; left: calc(50.00000000000002% - 2px / 2); overflow: hidden; position: absolute; top: 6px; width: 2px; will-change: var(--framer-will-change-override, transform); }", ".framer-3KZCs.framer-v-1eng780 .framer-1mx51vr { bottom: 6px; height: 5px; top: unset; }", '.framer-3KZCs[data-border="true"]::after, .framer-3KZCs [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
var FramerVNz4Lo5j2 = withCSS(Component, css, "framer-3KZCs");
var stdin_default = FramerVNz4Lo5j2;
FramerVNz4Lo5j2.displayName = "Scroll";
FramerVNz4Lo5j2.defaultProps = { height: 32, width: 20 };
addPropertyControls(FramerVNz4Lo5j2, { variant: { options: ["nNDWW0Q0D", "TjB_9fLr7"], optionTitles: ["Scroll up", "Scroll down"], title: "Variant", type: ControlType.Enum }, mYmZWnDfm: { defaultValue: { borderColor: "var(--token-d77b16bb-1b8f-4385-b88c-a570a9eef29c, rgb(0, 0, 0))", borderStyle: "solid", borderWidth: 1 }, title: "Border", type: ControlType.Border }, xE7or5QVg: { defaultValue: "var(--token-d77b16bb-1b8f-4385-b88c-a570a9eef29c, rgb(0, 0, 0))", title: "Background", type: ControlType.Color } });
addFonts(FramerVNz4Lo5j2, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:scroll
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "nNDWW0Q0D"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "B3FNg4k_A": { "path": "/404" }, "I9RkjucP4": { "path": "/legal/:slug" }, "LRbug5v4t": { "path": "/workshops" }, "NyXcQ0q58": { "path": "/workshops/:slug" }, "RW9KK4MDB": { "path": "/contact" }, "augiA20Il": { "path": "/" }, "kSNNxgO_v": { "path": "/about-us" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "B3FNg4k_A": {
          "path": "/404"
        },
        "I9RkjucP4": {
          "path": "/legal/:slug"
        },
        "LRbug5v4t": {
          "path": "/workshops"
        },
        "NyXcQ0q58": {
          "path": "/workshops/:slug"
        },
        "RW9KK4MDB": {
          "path": "/contact"
        },
        "augiA20Il": {
          "path": "/"
        },
        "kSNNxgO_v": {
          "path": "/about-us"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
