// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e581698183ded160 "ERIS Drexel Drone", do not edit manually */
"use client";
import {
  stdin_default
} from "./chunks/chunk-HFB6NF5Z.js";
import "./chunks/chunk-BTSBQWPZ.js";

// virtual:social-icon
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "Ps8iPYsCJ",
  "xl": "w4QgrJY8C"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "B3FNg4k_A": { "path": "/404" }, "I9RkjucP4": { "path": "/legal/:slug" }, "LRbug5v4t": { "path": "/workshops" }, "NyXcQ0q58": { "path": "/workshops/:slug" }, "RW9KK4MDB": { "path": "/contact" }, "augiA20Il": { "path": "/" }, "kSNNxgO_v": { "path": "/about-us" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "B3FNg4k_A": {
          "path": "/404"
        },
        "I9RkjucP4": {
          "path": "/legal/:slug"
        },
        "LRbug5v4t": {
          "path": "/workshops"
        },
        "NyXcQ0q58": {
          "path": "/workshops/:slug"
        },
        "RW9KK4MDB": {
          "path": "/contact"
        },
        "augiA20Il": {
          "path": "/"
        },
        "kSNNxgO_v": {
          "path": "/about-us"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "e581698183ded16063fff1fc4bda07aa7a061e04b84e89fd0c37a051cf96919a",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
